### ISSUE TITLE
DONE

### ISSUE THREAD

**Issue by Ypsilonx** [Ypsilonx/Czechitas_Python_1_kurz#2]
**Prosím, že to mám dobře?**

[Domácí úkol číslo 2](https://github.com/Ypsilonx/Czechitas_Python_1_kurz/blob/Python-1/07_ukol_02.py)

Když tak si s tím ještě pohraju - v tomhle jsem expert-hračička.
Nicméně dotazy budu směřovat na SLACK.

**Comment by M-Kovar** [comment]
Díky za bleskurychlé odevzdání. Zatím jsem se na to díval jen zrychleně a druhá část vypadá velmi dobře a funkčně:). První část v principu taky dobrý, ale chtělo by to vylepšit, ať napíše "neznámý region" jen jednou. Třeba by pomohlo ve for cyklu kromě printování ty státy v regionu i nějak sbírat a pak se podívat, kolik se jich posbíralo... (pokouším se to psát neurčitě, aby ti dopřál ještě trochu lámáni si hlavy, ale kdyby to nešlo, můžu dát další nápovědu:).

**Comment by Ypsilonx** [comment]
Ty brďo já jsem pako fakt :D 
Asi jsem na to přišel... 
Hodil jsem to do souboru - aktualizoval jsme ho.

Tak koukni teď očkem. 

Díky moc.

P.S.: Mě fakt dělá strašný problém pochopit to zadání... i na tom kódím.cz. S tímto asi budu bojovat dlouho.

**Comment by M-Kovar** [comment]
Paráda, teď to vypadá dobře:). Zatím neuzavírám, večer se ještě mrknu podrobněji, ale všechno se zdá být OK. S tím sbíráním států by šla ještě druhá možnost: dát append pod `if region == jaky_region` a tam sbírat jen státy v regionu (ideálně nejen název, ale celý slovník) a následně se podívat, jestli je seznam prázdný (pokud jo, znamená to neexistující region). Zároveň by takový seznam šel rovnou využít v bonusové druhé části.

**Comment by Ypsilonx** [comment]
Počkej, prosím tě -> zkoušel jsem tvořit slovník - ale .append pro slovník mi nejde - na to je jiná finta? Nebo jsem to psal blbě? :D

**Comment by M-Kovar** [comment]
Appendem bys přidával celý slovník (tzn. celý stát) do seznamu, což by mělo fungovat. Něco takového:

`staty_v_regionu = []`
a pak
`staty_v_regionu.append(item)`

Vlastně by sis tím vytvořil stejný seznam jako původní "staty", akorát by tam byly pouze státy z vybraného regionu.

**Comment by Ypsilonx** [comment]
To je ale furt seznam a ne slovník... teď si mě hodně zmátl...

**Comment by M-Kovar** [comment]
:D To jsem se předtím asi blbě vyjádřil. Ano, je to seznam. Myslím to tak, že státy v regionu sbíráme do normálního seznamu a každá položka toho seznamu je slovník, který obsahuje data o jednom státu (takže stejný formát jako ten vstupní seznam "staty"). Jestli jsem tě zmátl ještě víc, klidně se ptej dál.

**Comment by Ypsilonx** [comment]
Tak jsem tam doplnil do prvního fáze úkolu ty státy bez regionu - asi by to šlo udělat přes vytvořenou funkci aby to bylo hezčí, ale nechal jsem to takto... Je to OK.
Ještě  jsem si pohrál i s tou druhou fází úkolu, ale zajímalo by mě - lze ten slovník vypsat v printu bez těch závorek?... třeba jako seznam nebo to už nemám řešit?

Díky za odpověď.

**Comment by M-Kovar** [comment]
Ahoj Tome, dobrá práce, funguje to, udělal jsi i bonus a vypisování států bez regionu, paráda:). V zásadě nemám co vytknout, takže posílám jen následující drobnosti:

- `print(f'V regionu {jaky_region} jsou:')` přesuňme před for cyklus, ať se to nevypisuje pořád. Ale je mi jasný, že se to tam zatoulalo jen omylem.
- Zamyšlení nad optimalizací: Chápu, že jsi asi chtěl mít základní, bonusovou a "bezregionovou" část odděleně, ale ty části by případně šly sloučit tak, aby se slovník neprocházel třikrát celý, ale o něco méněkrát, tzn. aby se zkrátil čas běhu programu. Teď je to úplně jedno, rozdíl nepoznáme, píšu to spíš pro zajímavost a budování správných návyků, ale s násobně více daty už by třeba mohl být problém. Samozřejmě by bylo potřeba tam udělat pár dalších úprav, aby to fungovalo. Pro porovnání, tady jsem se pokusil počet cyklů zredukovat (a asi by to šlo ještě víc):
```
region_zajmu = input("Zadej region zájmu: ")
staty_v_regionu_zajmu = []
print(f"Státy v regionu {region_zajmu}")
for stat in staty:
    if stat["region"] == region_zajmu:
        staty_v_regionu_zajmu.append(stat)
        print(f" - {stat['name']}")

populace_subregionu = {}
# Pokud se do seznamu nějaké státy uložily:
if staty_v_regionu_zajmu:
    for stat in staty_v_regionu_zajmu:
        subregion = stat["subregion"]
        if subregion not in populace_subregionu:
            populace_subregionu[subregion] = 0
        populace_subregionu[subregion] += stat["population"]
    print(f"Populace subregionů v regionu {region_zajmu}: {populace_subregionu}")
# Pokud je seznam prázdný:
else:
    print("Neznámý region")
```

Lze slovník vypsat v printu bez závorek? --> Jasně, nejsnáz pomocí for cyklu a items(). Pak si to můžeš vyšperkovat podle libosti:).
```
for subregion,populace in celk_populace.items():
    print(f"{subregion}: {populace}")
```

**Comment by M-Kovar** [comment]
No jo, povídám tady něco o optimalizaci, a přitom mi až teď došlo, že i v tom svém řešení se můžu zbavit druhého foru:) ...
```
region_zajmu = input("Zadej region zájmu: ")
staty_v_regionu_zajmu = []
populace_subregionu = {}
print(f"Státy v regionu {region_zajmu}")
for stat in staty:
    if stat["region"] == region_zajmu:
        staty_v_regionu_zajmu.append(stat)
        print(f" - {stat['name']}")
        subregion = stat["subregion"]
        if subregion not in populace_subregionu:
            populace_subregionu[subregion] = 0
        populace_subregionu[subregion] += stat["population"]
        
if populace_subregionu:
    print(populace_subregionu)
else:
    print("Neznámý region")
```
